force-app/main/default/objects/Language_Course__c/Language_Course__c.object-meta.xml
<CustomObject>
    <label>Language Course</label>
    <nameField>
        <label>Language Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Language_Course__c/fields/Course_Instructor__c.field-meta.xml
<CustomField>
    <fullName>Course_Instructor__c</fullName>
    <description>Teacher for the language course</description>
    <label>Language Course Instructor</label>
    <referenceTo>Language_Course_Instructor__c</referenceTo>
    <relationshipLabel>Language Courses</relationshipLabel>
    <relationshipName>Language_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Language_Course_Designer__c/Language_Course_Designer__c.object-meta.xml
<CustomObject>
    <label>Language Course Designer</label>
    <nameField>
        <label>Language Course Designer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Course Designers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language_Course_Instructor__c/Language_Course_Instructor__c.object-meta.xml
<CustomObject>
    <label>Language Course Instructor</label>
    <nameField>
        <label>Language Course Instructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Course Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestLanguageCourseTrigger.cls
@isTest
private class TestLanguageCourseTrigger {
     
    public static testmethod void myTessst() {
        
        Language_Course_Designer__c f = new Language_Course_Designer__c();
        f.Name = 'Javier Santiago';
        insert f;
        
        Language_Course_Instructor__c x = new Language_Course_Instructor__c();
        x.name = 'Ed Santiago';
        insert x;
        
        Test.startTest();
        Language_Course__c a = new Language_Course__c();
        a.name = 'My custom name';
        a.Course_Instructor__c = x.id;
        a.Language_Course_Designer__c = f.id;
        
        insert a;
       
        Test.stopTest();
         system.assertEquals('My custom name', a.name, 'it works');
    }
    
    
}